evaluate-commands %sh{
  PLUGINS_DIR="${HOME}/.cache/kak/plugins"
  mkdir -p "${PLUGINS_DIR}"

  if [ ! -e "${PLUGINS_DIR}/plug.kak" ]; then
    git clone -q "https://github.com/andreyorst/plug.kak.git" "${PLUGINS_DIR}/plug.kak"
  fi

  printf "%s\n" "source '${PLUGINS_DIR}/plug.kak/rc/plug.kak'"
}

plug "andreyorst/plug.kak" noload config %{
  set-option global plug_install_dir %sh{ echo "${HOME}/.cache/kak/plugins" }
}

plug "kakoune-editor/kakoune-extra-filetypes"

# clipboard integration
plug "lePerdu/kakboard" %{
  hook global WinCreate .* %{ kakboard-enable }
}

plug "danr/kakoune-easymotion" config %{
  map global normal <ret> ':enter-user-mode easymotion<ret>'
}
#plug "alexherbo2/auto-pairs.kak" # @TODO find an alternative

# plug https://github.com/alexherbo2/surround.kak

plug "kak-lsp/kak-lsp" do %{
  cargo build --release --locked
  cargo install --force --path .
} config %{
  set-option global lsp_auto_highlight_references true
  set-option global lsp_hover_anchor false
  lsp-auto-hover-enable

  #eval %sh{kak-lsp --kakoune -s $kak_session}
  lsp-enable

  hook global KakEnd .* lsp-exit
}

plug "whereswaldon/shellcheck.kak"

plug "andreyorst/fzf.kak" defer "fzf" %{
  set-option global fzf_implementation 'sk' # cargo install skim
  set-option global fzf_file_command 'rg' # cargo install ripgrep
  require-module fzf

} config %{
  map -docstring 'Fuzzy find' global user <space> ': fzf-mode<ret>'
}

colorscheme nord
add-highlighter global/insecable regex ' +' 0:default,black

# Indentation management
set global tabstop 2
set global indentwidth 2
hook global InsertChar \t %{ exec -draft -itersel h@ }
# Specific types
hook global WinSetOption filetype=(rust|python) %{
  set global tabstop 4
  set global indentwidth 4
}

# Use tab for auto completion
hook global InsertCompletionShow .* %{
  try %{
    map window insert <tab> <c-n>
    map window insert <s-tab> <c-p>
  }
}
hook global InsertCompletionHide .* %{
  unmap window insert <tab> <c-n>
  unmap window insert <s-tab> <c-p>
}

# Other completion option
#set-option global ignored_files '~$'

#map global normal <space> ':enter-user-mode user<ret>'
map -docstring 'Comment' global user c :comment-line<ret>
map -docstring 'Save' global user , :w<ret>
map -docstring 'Close buffer' global user q :db<ret>
map -docstring 'Save and quit' global user w :wq<ret>
map -docstring 'Quit without saving' global user <s-q> :q!<ret>

# wrap text
addhl -override global/ wrap -word

# dynamic numbers (switch between absolute and relative followinf insert and other modes)
def set-line-numbers-relatives %{
  remove-highlighter window/line-numbers
  add-highlighter window/line-numbers number-lines -relative -hlcursor -min-digits 4
}
def set-line-numbers-absolutes %{
  remove-highlighter window/line-numbers
  add-highlighter window/line-numbers number-lines -hlcursor -min-digits 4
}
hook global WinCreate .* %{ set-line-numbers-relatives }
hook global ModeChange push:normal:insert %{ set-line-numbers-absolutes }
hook global ModeChange pop:insert:normal %{ set-line-numbers-relatives }

# splits/windows management (with Tmux)
declare-user-mode windows
map -docstring 'Enter windows management mode' global normal = ':enter-user-mode windows<ret>'
map -docstring 'New window' global windows c ':tmux-terminal-window kak -c %val{session}<ret>'
map -docstring 'Close' global windows q ':q<ret>'
map -docstring 'Split vertically' global windows v ':tmux-terminal-vertical kak -c %val{session}<ret>'
map -docstring 'Split horizontally' global windows h ':tmux-terminal-horizontal kak -c %val{session}<ret>'

def find -params 1 -shell-script-candidates %{ find -type f } %{ edit %arg{1} }

# show and remove trailing whitespaces
define-command -hidden show-trailing-whitespaces %{
  try %{
    add-highlighter global/trailing-whitespaces regex '\h+$' 0:default,red
  }
}
define-command -hidden hide-trailing-whitespaces %{
  try %{
    remove-highlighter global/trailing-whitespaces
  }
}
define-command -hidden remove-trailing-whitespaces %{
  try %{
    exec -draft '%s\h+$<ret>d'
  }
}
hook global WinDisplay .*              show-trailing-whitespaces
hook global ModeChange 'insert:normal' show-trailing-whitespaces
hook global ModeChange 'normal:insert' hide-trailing-whitespaces
hook global BufWritePre .*             remove-trailing-whitespaces

# disable scratc buffer message
#set global disabled_hooks write-scratch-message

# see `:doc options` to modify status line (modelinefmt)

# config reload
map -docstring "Reload configuration" global user r ":source %val{config}/kakrc"
